import '@/scss/config/base.scss';
import '@/scss/config/fonts.scss';
import '@/scss/config/functions.scss';
import '@/scss/config/keyframes.scss';
import '@/scss/config/mixins.scss';
import '@/scss/config/placeholders.scss';
import '@/scss/config/reset.scss';
import '@/scss/config/root.scss';
import '@/scss/config/typography.scss';
import '@/scss/main.scss';
import type { Metadata } from "next";
import '../scss/config/fonts.scss';


import 'swiper/css'
import 'swiper/css/navigation'

import { Montserrat, Philosopher } from 'next/font/google';

const philosopher = Philosopher({
  subsets: ['latin', 'cyrillic'],
  weight: ['400', '700'],
  display: 'swap',
  variable: '--font-philosopher', 
});

const montserrat = Montserrat({
  subsets: ['latin', 'cyrillic'],
  weight: ['400', '700', '500', '300', '600'],
  display: 'swap',
  variable: '--font-montserrat', 
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className={`${philosopher.variable} ${montserrat.variable}`} lang="ru">
      <body>
        <div >
        {children}
        </div>
      </body>
    </html>
  );
}
